--
-- Volcado de datos para la tabla `role`
--
INSERT INTO `role` (`id`, `role`) VALUES (1, 'ADMIN');
INSERT INTO `role` (`id`, `role`) VALUES (2, 'USER');



--
-- Volcado de datos para la tabla `user`
--
INSERT INTO `user` (`id`, `active`, `email`, `firstname`, `lastname`, `password`, `ubigeo`) VALUES ('1', b'1', 'admin', 'Name', 'Last Name', '$2a$10$a3x2CGSlVK4bjGrFlDX5SuLp4u98Zn0S7g5KSAotut24JMU2GoSIC', '150101');



--
-- Volcado de datos para la tabla `user_role`
--
INSERT INTO `user_role` (`user_id`, `role_id`) VALUES (1, 1);



--
-- Volcado de datos para la tabla `ubigeo`
--
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('010000','AMAZONAS', '','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('010100','AMAZONAS','CHACHAPOYAS','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('010101','AMAZONAS','CHACHAPOYAS','CHACHAPOYAS ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('010102','AMAZONAS','CHACHAPOYAS','ASUNCIÓN');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('010103','AMAZONAS','CHACHAPOYAS','BALSAS  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('010518','AMAZONAS','LUYA','SAN JERÓNIMO');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('010703','AMAZONAS','UTCUBAMBA ','CUMBA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('010704','AMAZONAS','UTCUBAMBA ','EL MILAGRO  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('010705','AMAZONAS','UTCUBAMBA ','JAMALCA ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('010706','AMAZONAS','UTCUBAMBA ','LONYA GRANDE');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('010707','AMAZONAS','UTCUBAMBA ','YAMON');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('020000','ÁNCASH' , '','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('020100','ÁNCASH','HUARAZ','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('020101','ÁNCASH','HUARAZ','HUARAZ  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('020102','ÁNCASH','HUARAZ','COCHABAMBA  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('020103','ÁNCASH','HUARAZ','COLCABAMBA  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('022001','ÁNCASH','YUNGAY','YUNGAY  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('022002','ÁNCASH','YUNGAY','CASCAPARA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('022003','ÁNCASH','YUNGAY','MANCOS  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('022004','ÁNCASH','YUNGAY','MATACOTO');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('030209','APURÍMAC','ANDAHUAYLAS','PACUCHA ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('030210','APURÍMAC','ANDAHUAYLAS','PAMPACHIRI  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('030211','APURÍMAC','ANDAHUAYLAS','POMACOCHA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('030212','APURÍMAC','ANDAHUAYLAS','SAN ANTONIO DE CACHI');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('030213','APURÍMAC','ANDAHUAYLAS','SAN JERÓNIMO');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('030214','APURÍMAC','ANDAHUAYLAS','SAN MIGUEL DE CHACCRAMPA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('030215','APURÍMAC','ANDAHUAYLAS','SANTA MARÍA DE CHICMO');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('030710','APURÍMAC','GRAU','SANTA ROSA  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('030711','APURÍMAC','GRAU','TURPAY  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('030712','APURÍMAC','GRAU','VILCABAMBA  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('030713','APURÍMAC','GRAU','VIRUNDO ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('030714','APURÍMAC','GRAU','CURASCO ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('040000','AREQUIPA', '','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('040100','AREQUIPA','AREQUIPA','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('040123','AREQUIPA','AREQUIPA','TIABAYA ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('040124','AREQUIPA','AREQUIPA','UCHUMAYO');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('040125','AREQUIPA','AREQUIPA','VITOR');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('040126','AREQUIPA','AREQUIPA','YANAHUARA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('040127','AREQUIPA','AREQUIPA','YARABAMBA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('040128','AREQUIPA','AREQUIPA','YURA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('040129','AREQUIPA','AREQUIPA','JOSÉ LUIS BUSTAMANTE Y RIVERO');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('040200','AREQUIPA','CAMANÁ','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('040201','AREQUIPA','CAMANÁ','CAMANÁ  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('040808','AREQUIPA','LA UNIÒN','SAYLA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('040809','AREQUIPA','LA UNIÒN','TAURIA  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('040810','AREQUIPA','LA UNIÒN','TOMEPAMPA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('040811','AREQUIPA','LA UNIÒN','TORO');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('050000','AYACUCHO', '','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('050100','AYACUCHO','HUAMANGA','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('050101','AYACUCHO','HUAMANGA','AYACUCHO');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('050102','AYACUCHO','HUAMANGA','ACOCRO  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('050103','AYACUCHO','HUAMANGA','ACOS VINCHOS');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('050500','AYACUCHO','LA MAR','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('050810','AYACUCHO','PÀUCAR DEL SARA SARA','SARA SARA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('050900','AYACUCHO','SUCRE ','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('051107','AYACUCHO','VILCAS HUAMÁN ','SAURAMA ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('051108','AYACUCHO','VILCAS HUAMÁN ','VISCHONGO');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('060000','CAJAMARCA ' , '','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('060100','CAJAMARCA ','CAJAMARCA ','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('060101','CAJAMARCA ','CAJAMARCA ','CAJAMARCA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('060102','CAJAMARCA ','CAJAMARCA ','ASUNCIÓN');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('061101','CAJAMARCA ','SAN MIGUEL','SAN MIGUEL  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('061102','CAJAMARCA ','SAN MIGUEL','BOLÍVAR ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('061103','CAJAMARCA ','SAN MIGUEL','CALQUIS ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('070000','CALLAO' , '','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('070100','CALLAO','PROV. CONST. DEL CALLAO','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('070101','CALLAO','PROV. CONST. DEL CALLAO','CALLAO  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('070102','CALLAO','PROV. CONST. DEL CALLAO','BELLAVISTA  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('070103','CALLAO','PROV. CONST. DEL CALLAO','CARMEN DE LA LEGUA REYNOSO  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('070104','CALLAO','PROV. CONST. DEL CALLAO','LA PERLA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('070105','CALLAO','PROV. CONST. DEL CALLAO','LA PUNTA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('070106','CALLAO','PROV. CONST. DEL CALLAO','VENTANILLA  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('070107','CALLAO','PROV. CONST. DEL CALLAO','MI PERÚ ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('080000','CUSCO ' , '','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('080100','CUSCO ','CUSCO ','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('080101','CUSCO ','CUSCO ','CUSCO');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('080102','CUSCO ','CUSCO ','CCORCA  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('080103','CUSCO ','CUSCO ','POROY');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('080104','CUSCO ','CUSCO ','SAN JERÓNIMO');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('080603','CUSCO ','CANCHIS','COMBAPATA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('080604','CUSCO ','CANCHIS','MARANGANI');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('080605','CUSCO ','CANCHIS','PITUMARCA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('080606','CUSCO ','CANCHIS','SAN PABLO');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('080807','CUSCO ','ESPINAR','SUYCKUTAMBO ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('080808','CUSCO ','ESPINAR','ALTO PICHIGUA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('080900','CUSCO ','LA CONVENCIÓN ','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('080901','CUSCO ','LA CONVENCIÓN ','SANTA ANA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('081306','CUSCO ','URUBAMBA','OLLANTAYTAMBO');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('081307','CUSCO ','URUBAMBA','YUCAY');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('090000','HUANCAVELICA', '','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('090100','HUANCAVELICA','HUANCAVELICA','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('090101','HUANCAVELICA','HUANCAVELICA','HUANCAVELICA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('090102','HUANCAVELICA','HUANCAVELICA','ACOBAMBILLA ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('090103','HUANCAVELICA','HUANCAVELICA','ACORIA  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('090104','HUANCAVELICA','HUANCAVELICA','CONAYCA ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('090303','HUANCAVELICA','ANGARAES','CALLANMARCA ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('090304','HUANCAVELICA','ANGARAES','CCOCHACCASA ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('090704','HUANCAVELICA','TAYACAJA','AHUAYCHA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('090705','HUANCAVELICA','TAYACAJA','COLCABAMBA  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('090706','HUANCAVELICA','TAYACAJA','DANIEL HERNÁNDEZ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('090707','HUANCAVELICA','TAYACAJA','HUACHOCOLPA ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('090709','HUANCAVELICA','TAYACAJA','HUARIBAMBA  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('090710','HUANCAVELICA','TAYACAJA','ÑAHUIMPUQUIO');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('100111','HUÁNUCO','HUÁNUCO','PILLCO MARCA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('100112','HUÁNUCO','HUÁNUCO','YACUS');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('100200','HUÁNUCO','AMBO','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('100201','HUÁNUCO','AMBO','AMBO');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('100202','HUÁNUCO','AMBO','CAYNA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('100203','HUÁNUCO','AMBO','COLPAS  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('100204','HUÁNUCO','AMBO','CONCHAMARCA ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('100205','HUÁNUCO','AMBO','HUACAR  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('100502','HUÁNUCO','HUAMALÍES ','ARANCAY ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('100503','HUÁNUCO','HUAMALÍES ','CHAVÍN DE PARIARCA  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('100504','HUÁNUCO','HUAMALÍES ','JACAS GRANDE');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('100505','HUÁNUCO','HUAMALÍES ','JIRCAN  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('100506','HUÁNUCO','HUAMALÍES ','MIRAFLORES  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('100507','HUÁNUCO','HUAMALÍES ','MONZÓN  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('100508','HUÁNUCO','HUAMALÍES ','PUNCHAO ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('100509','HUÁNUCO','HUAMALÍES ','PUÑOS');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('101106','HUÁNUCO','YAROWILCA ','OBAS');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('101107','HUÁNUCO','YAROWILCA ','PAMPAMARCA  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('101108','HUÁNUCO','YAROWILCA ','CHORAS  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('110000','ICA' , '','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('110100','ICA','ICA','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('110101','ICA','ICA','ICA ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('110102','ICA','ICA','LA TINGUIÑA ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('110103','ICA','ICA','LOS AQUIJES ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('110104','ICA','ICA','OCUCAJE ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('110105','ICA','ICA','PACHACUTEC  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('110106','ICA','ICA','PARCONA ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('110107','ICA','ICA','PUEBLO NUEVO');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('110108','ICA','ICA','SALAS');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('110109','ICA','ICA','SAN JOSÉ DE LOS MOLINOS ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('110110','ICA','ICA','SAN JUAN BAUTISTA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('110111','ICA','ICA','SANTIAGO');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('110112','ICA','ICA','SUBTANJALLA ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('110113','ICA','ICA','TATE');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('110114','ICA','ICA','YAUCA DEL ROSARIO');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('110200','ICA','CHINCHA','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('110201','ICA','CHINCHA','CHINCHA ALTA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('110202','ICA','CHINCHA','ALTO LARAN  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('110203','ICA','CHINCHA','CHAVIN  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('110503','ICA','PISCO ','HUMAY');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('110506','ICA','PISCO ','SAN ANDRÉS  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('110507','ICA','PISCO ','SAN CLEMENTE');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('110508','ICA','PISCO ','TUPAC AMARU INCA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('120000','JUNÍN ' , '','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('120100','JUNÍN ','HUANCAYO','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('120101','JUNÍN ','HUANCAYO','HUANCAYO');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('120104','JUNÍN ','HUANCAYO','CARHUACALLANGA  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('120105','JUNÍN ','HUANCAYO','CHACAPAMPA  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('120106','JUNÍN ','HUANCAYO','CHICCHE ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('120411','JUNÍN ','JAUJA ','JANJAILLO');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('120412','JUNÍN ','JAUJA ','JULCÁN  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('120413','JUNÍN ','JAUJA ','LEONOR ORDÓÑEZ  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('120414','JUNÍN ','JAUJA ','LLOCLLAPAMPA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('120415','JUNÍN ','JAUJA ','MARCO');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('120416','JUNÍN ','JAUJA ','MASMA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('120700','JUNÍN ','TARMA ','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('120706','JUNÍN ','TARMA ','PALCA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('120707','JUNÍN ','TARMA ','PALCAMAYO');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('120708','JUNÍN ','TARMA ','SAN PEDRO DE CAJAS  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('120709','JUNÍN ','TARMA ','TAPO');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('120800','JUNÍN ','YAULI ','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('120801','JUNÍN ','YAULI ','LA OROYA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('120908','JUNÍN ','CHUPACA','TRES DE DICIEMBRE');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('120909','JUNÍN ','CHUPACA','YANACANCHA  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('130000','LA LIBERTAD' , '','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('130100','LA LIBERTAD','TRUJILLO','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('130101','LA LIBERTAD','TRUJILLO','TRUJILLO');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('130102','LA LIBERTAD','TRUJILLO','EL PORVENIR ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('130103','LA LIBERTAD','TRUJILLO','FLORENCIA DE MORA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('130104','LA LIBERTAD','TRUJILLO','HUANCHACO');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('130105','LA LIBERTAD','TRUJILLO','LA ESPERANZA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('131201','LA LIBERTAD','VIRÚ','VIRU');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('131202','LA LIBERTAD','VIRÚ','CHAO');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('131203','LA LIBERTAD','VIRÚ','GUADALUPITO ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('140000','LAMBAYEQUE' , '','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('140100','LAMBAYEQUE','CHICLAYO','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('140101','LAMBAYEQUE','CHICLAYO','CHICLAYO');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('140102','LAMBAYEQUE','CHICLAYO','CHONGOYAPE  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('140103','LAMBAYEQUE','CHICLAYO','ETEN');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('140104','LAMBAYEQUE','CHICLAYO','ETEN PUERTO ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('140115','LAMBAYEQUE','CHICLAYO','SAÑA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('140308','LAMBAYEQUE','LAMBAYEQUE','OLMOS');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('140309','LAMBAYEQUE','LAMBAYEQUE','PACORA  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('140310','LAMBAYEQUE','LAMBAYEQUE','SALAS');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('140311','LAMBAYEQUE','LAMBAYEQUE','SAN JOSÉ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('140312','LAMBAYEQUE','LAMBAYEQUE','TUCUME  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150000','LIMA', '','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150100','LIMA','LIMA','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150101','LIMA','LIMA','LIMA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150102','LIMA','LIMA','ANCÓN');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150103','LIMA','LIMA','ATE ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150104','LIMA','LIMA','BARRANCO');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150105','LIMA','LIMA','BREÑA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150106','LIMA','LIMA','CARABAYLLO  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150107','LIMA','LIMA','CHACLACAYO  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150108','LIMA','LIMA','CHORRILLOS  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150109','LIMA','LIMA','CIENEGUILLA ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150110','LIMA','LIMA','COMAS');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150111','LIMA','LIMA','EL AGUSTINO ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150112','LIMA','LIMA','INDEPENDENCIA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150113','LIMA','LIMA','JESÚS MARÍA ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150114','LIMA','LIMA','LA MOLINA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150115','LIMA','LIMA','LA VICTORIA ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150116','LIMA','LIMA','LINCE');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150117','LIMA','LIMA','LOS OLIVOS  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150118','LIMA','LIMA','LURIGANCHO  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150119','LIMA','LIMA','LURIN');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150120','LIMA','LIMA','MAGDALENA DEL MAR');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150121','LIMA','LIMA','PUEBLO LIBRE');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150122','LIMA','LIMA','MIRAFLORES  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150123','LIMA','LIMA','PACHACAMAC  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150124','LIMA','LIMA','PUCUSANA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150125','LIMA','LIMA','PUENTE PIEDRA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150126','LIMA','LIMA','PUNTA HERMOSA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150127','LIMA','LIMA','PUNTA NEGRA ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150128','LIMA','LIMA','RÍMAC');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150129','LIMA','LIMA','SAN BARTOLO ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150130','LIMA','LIMA','SAN BORJA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150131','LIMA','LIMA','SAN ISIDRO  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150132','LIMA','LIMA','SAN JUAN DE LURIGANCHO  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150133','LIMA','LIMA','SAN JUAN DE MIRAFLORES  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150134','LIMA','LIMA','SAN LUIS');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150135','LIMA','LIMA','SAN MARTÍN DE PORRES');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150136','LIMA','LIMA','SAN MIGUEL  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150137','LIMA','LIMA','SANTA ANITA ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150138','LIMA','LIMA','SANTA MARÍA DEL MAR ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150139','LIMA','LIMA','SANTA ROSA  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150140','LIMA','LIMA','SANTIAGO DE SURCO');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150141','LIMA','LIMA','SURQUILLO');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150142','LIMA','LIMA','VILLA EL SALVADOR');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150143','LIMA','LIMA','VILLA MARÍA DEL TRIUNFO ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150200','LIMA','BARRANCA','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150201','LIMA','BARRANCA','BARRANCA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150202','LIMA','BARRANCA','PARAMONGA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150203','LIMA','BARRANCA','PATIVILCA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150204','LIMA','BARRANCA','SUPE');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150205','LIMA','BARRANCA','SUPE PUERTO ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150300','LIMA','CAJATAMBO ','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150301','LIMA','CAJATAMBO ','CAJATAMBO');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150302','LIMA','CAJATAMBO ','COPA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150303','LIMA','CAJATAMBO ','GORGOR  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150304','LIMA','CAJATAMBO ','HUANCAPON');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150305','LIMA','CAJATAMBO ','MANAS');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150400','LIMA','CANTA ','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150401','LIMA','CANTA ','CANTA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150402','LIMA','CANTA ','ARAHUAY ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150403','LIMA','CANTA ','HUAMANTANGA ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150404','LIMA','CANTA ','HUAROS  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150405','LIMA','CANTA ','LACHAQUI');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150406','LIMA','CANTA ','SAN BUENAVENTURA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150407','LIMA','CANTA ','SANTA ROSA DE QUIVES');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150500','LIMA','CAÑETE','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150501','LIMA','CAÑETE','SAN VICENTE DE CAÑETE');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150502','LIMA','CAÑETE','ASIA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150503','LIMA','CAÑETE','CALANGO ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150504','LIMA','CAÑETE','CERRO AZUL  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150505','LIMA','CAÑETE','CHILCA  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150506','LIMA','CAÑETE','COAYLLO ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150507','LIMA','CAÑETE','IMPERIAL');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150508','LIMA','CAÑETE','LUNAHUANA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150509','LIMA','CAÑETE','MALA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150510','LIMA','CAÑETE','NUEVO IMPERIAL  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150511','LIMA','CAÑETE','PACARAN ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150512','LIMA','CAÑETE','QUILMANA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150513','LIMA','CAÑETE','SAN ANTONIO ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150514','LIMA','CAÑETE','SAN LUIS');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150515','LIMA','CAÑETE','SANTA CRUZ DE FLORES');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150516','LIMA','CAÑETE','ZÚÑIGA  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150600','LIMA','HUARAL','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150601','LIMA','HUARAL','HUARAL  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150602','LIMA','HUARAL','ATAVILLOS ALTO  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150603','LIMA','HUARAL','ATAVILLOS BAJO  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150604','LIMA','HUARAL','AUCALLAMA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150605','LIMA','HUARAL','CHANCAY ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150606','LIMA','HUARAL','IHUARI  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150607','LIMA','HUARAL','LAMPIAN ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150608','LIMA','HUARAL','PACARAOS');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150609','LIMA','HUARAL','SAN MIGUEL DE ACOS  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150610','LIMA','HUARAL','SANTA CRUZ DE ANDAMARCA ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150611','LIMA','HUARAL','SUMBILCA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150612','LIMA','HUARAL','VEINTISIETE DE NOVIEMBRE');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150700','LIMA','HUAROCHIRÍ','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150701','LIMA','HUAROCHIRÍ','MATUCANA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150702','LIMA','HUAROCHIRÍ','ANTIOQUIA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150703','LIMA','HUAROCHIRÍ','CALLAHUANCA ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150704','LIMA','HUAROCHIRÍ','CARAMPOMA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150705','LIMA','HUAROCHIRÍ','CHICLA  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150706','LIMA','HUAROCHIRÍ','CUENCA  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150707','LIMA','HUAROCHIRÍ','HUACHUPAMPA ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150708','LIMA','HUAROCHIRÍ','HUANZA  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150709','LIMA','HUAROCHIRÍ','HUAROCHIRI  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150710','LIMA','HUAROCHIRÍ','LAHUAYTAMBO ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150711','LIMA','HUAROCHIRÍ','LANGA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150712','LIMA','HUAROCHIRÍ','LARAOS  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150713','LIMA','HUAROCHIRÍ','MARIATANA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150714','LIMA','HUAROCHIRÍ','RICARDO PALMA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150715','LIMA','HUAROCHIRÍ','SAN ANDRÉS DE TUPICOCHA ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150716','LIMA','HUAROCHIRÍ','SAN ANTONIO ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150717','LIMA','HUAROCHIRÍ','SAN BARTOLOMÉ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150718','LIMA','HUAROCHIRÍ','SAN DAMIAN  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150719','LIMA','HUAROCHIRÍ','SAN JUAN DE IRIS');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150720','LIMA','HUAROCHIRÍ','SAN JUAN DE TANTARANCHE ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150721','LIMA','HUAROCHIRÍ','SAN LORENZO DE QUINTI');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150722','LIMA','HUAROCHIRÍ','SAN MATEO');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150723','LIMA','HUAROCHIRÍ','SAN MATEO DE OTAO');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150724','LIMA','HUAROCHIRÍ','SAN PEDRO DE CASTA  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150725','LIMA','HUAROCHIRÍ','SAN PEDRO DE HUANCAYRE  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150726','LIMA','HUAROCHIRÍ','SANGALLAYA  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150727','LIMA','HUAROCHIRÍ','SANTA CRUZ DE COCACHACRA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150728','LIMA','HUAROCHIRÍ','SANTA EULALIA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150729','LIMA','HUAROCHIRÍ','SANTIAGO DE ANCHUCAYA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150730','LIMA','HUAROCHIRÍ','SANTIAGO DE TUNA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150731','LIMA','HUAROCHIRÍ','SANTO DOMINGO DE LOS OLLEROS');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150732','LIMA','HUAROCHIRÍ','SURCO');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150800','LIMA','HUAURA','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150801','LIMA','HUAURA','HUACHO  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150802','LIMA','HUAURA','AMBAR');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150803','LIMA','HUAURA','CALETA DE CARQUIN');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150804','LIMA','HUAURA','CHECRAS ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150805','LIMA','HUAURA','HUALMAY ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150806','LIMA','HUAURA','HUAURA  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150807','LIMA','HUAURA','LEONCIO PRADO');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150808','LIMA','HUAURA','PACCHO  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150809','LIMA','HUAURA','SANTA LEONOR');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150810','LIMA','HUAURA','SANTA MARÍA ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150811','LIMA','HUAURA','SAYAN');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150812','LIMA','HUAURA','VEGUETA ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150900','LIMA','OYÓN','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150901','LIMA','OYÓN','OYON');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150902','LIMA','OYÓN','ANDAJES ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150903','LIMA','OYÓN','CAUJUL  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150904','LIMA','OYÓN','COCHAMARCA  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150905','LIMA','OYÓN','NAVAN');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('150906','LIMA','OYÓN','PACHANGARA  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('151000','LIMA','YAUYOS','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('151001','LIMA','YAUYOS','YAUYOS  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('151002','LIMA','YAUYOS','ALIS');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('151003','LIMA','YAUYOS','ALLAUCA ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('151004','LIMA','YAUYOS','AYAVIRI ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('151005','LIMA','YAUYOS','AZÁNGARO');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('151006','LIMA','YAUYOS','CACRA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('151007','LIMA','YAUYOS','CARANIA ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('151008','LIMA','YAUYOS','CATAHUASI');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('151009','LIMA','YAUYOS','CHOCOS  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('151010','LIMA','YAUYOS','COCHAS  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('151011','LIMA','YAUYOS','COLONIA ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('151012','LIMA','YAUYOS','HONGOS  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('151013','LIMA','YAUYOS','HUAMPARA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('151014','LIMA','YAUYOS','HUANCAYA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('151015','LIMA','YAUYOS','HUANGASCAR  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('151016','LIMA','YAUYOS','HUANTAN ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('151017','LIMA','YAUYOS','HUAÑEC  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('151018','LIMA','YAUYOS','LARAOS  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('151019','LIMA','YAUYOS','LINCHA  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('151020','LIMA','YAUYOS','MADEAN  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('151021','LIMA','YAUYOS','MIRAFLORES  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('151022','LIMA','YAUYOS','OMAS');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('151023','LIMA','YAUYOS','PUTINZA ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('151024','LIMA','YAUYOS','QUINCHES');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('151025','LIMA','YAUYOS','QUINOCAY');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('151026','LIMA','YAUYOS','SAN JOAQUÍN ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('151027','LIMA','YAUYOS','SAN PEDRO DE PILAS  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('151028','LIMA','YAUYOS','TANTA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('151029','LIMA','YAUYOS','TAURIPAMPA  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('151030','LIMA','YAUYOS','TOMAS');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('151031','LIMA','YAUYOS','TUPE');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('151032','LIMA','YAUYOS','VIÑAC');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('151033','LIMA','YAUYOS','VITIS');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('160000','LORETO' , '','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('160100','LORETO','MAYNAS','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('160101','LORETO','MAYNAS','IQUITOS ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('160102','LORETO','MAYNAS','ALTO NANAY  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('160103','LORETO','MAYNAS','FERNANDO LORES  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('160104','LORETO','MAYNAS','INDIANA ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('160105','LORETO','MAYNAS','LAS AMAZONAS');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('160106','LORETO','MAYNAS','MAZAN');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('160107','LORETO','MAYNAS','NAPO');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('160108','LORETO','MAYNAS','PUNCHANA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('160110','LORETO','MAYNAS','TORRES CAUSANA  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('160112','LORETO','MAYNAS','BELÉN');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('160113','LORETO','MAYNAS','SAN JUAN BAUTISTA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('160200','LORETO','ALTO AMAZONAS ','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('160201','LORETO','ALTO AMAZONAS ','YURIMAGUAS  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('160202','LORETO','ALTO AMAZONAS ','BALSAPUERTO ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('160205','LORETO','ALTO AMAZONAS ','JEBEROS ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('160601','LORETO','UCAYALI','CONTAMANA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('160602','LORETO','UCAYALI','INAHUAYA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('160603','LORETO','UCAYALI','PADRE MÁRQUEZ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('160604','LORETO','UCAYALI','PAMPA HERMOSA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('160605','LORETO','UCAYALI','SARAYACU');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('160606','LORETO','UCAYALI','VARGAS GUERRA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('160700','LORETO','DATEM DEL MARAÑÓN ','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('160701','LORETO','DATEM DEL MARAÑÓN ','BARRANCA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('160702','LORETO','DATEM DEL MARAÑÓN ','CAHUAPANAS  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('160703','LORETO','DATEM DEL MARAÑÓN ','MANSERICHE  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('160704','LORETO','DATEM DEL MARAÑÓN ','MORONA  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('160705','LORETO','DATEM DEL MARAÑÓN ','PASTAZA ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('160706','LORETO','DATEM DEL MARAÑÓN ','ANDOAS  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('160800','LORETO','PUTUMAYO','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('160801','LORETO','PUTUMAYO','PUTUMAYO');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('160802','LORETO','PUTUMAYO','ROSA PANDURO');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('160803','LORETO','PUTUMAYO','TENIENTE MANUEL CLAVERO ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('160804','LORETO','PUTUMAYO','YAGUAS  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('170000','MADRE DE DIOS ' , '','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('170100','MADRE DE DIOS ','TAMBOPATA ','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('170302','MADRE DE DIOS ','TAHUAMANU ','IBERIA  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('170303','MADRE DE DIOS ','TAHUAMANU ','TAHUAMANU');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('180000','MOQUEGUA', '','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('180100','MOQUEGUA','MARISCAL NIETO','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('180101','MOQUEGUA','MARISCAL NIETO','MOQUEGUA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('180102','MOQUEGUA','MARISCAL NIETO','CARUMAS ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('180208','MOQUEGUA','GENERAL SÁNCHEZ CERRO ','PUQUINA ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('180209','MOQUEGUA','GENERAL SÁNCHEZ CERRO ','QUINISTAQUILLAS ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('180210','MOQUEGUA','GENERAL SÁNCHEZ CERRO ','UBINAS  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('180211','MOQUEGUA','GENERAL SÁNCHEZ CERRO ','YUNGA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('180300','MOQUEGUA','ILO','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('180301','MOQUEGUA','ILO','ILO ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('180302','MOQUEGUA','ILO','EL ALGARROBAL');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('180303','MOQUEGUA','ILO','PACOCHA ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('190000','PASCO ' , '','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('190100','PASCO ','PASCO ','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('190101','PASCO ','PASCO ','CHAUPIMARCA ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('190102','PASCO ','PASCO ','HUACHON ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('190103','PASCO ','PASCO ','HUARIACA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('190104','PASCO ','PASCO ','HUAYLLAY');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('190112','PASCO ','PASCO ','VICCO');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('190113','PASCO ','PASCO ','YANACANCHA  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('190200','PASCO ','DANIEL ALCIDES CARRIÓN','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('200110','PIURA ','PIURA ','LA UNIÓN');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('200111','PIURA ','PIURA ','LAS LOMAS');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('200114','PIURA ','PIURA ','TAMBO GRANDE');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('200115','PIURA ','PIURA ','VEINTISEIS DE OCTUBRE');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('200200','PIURA ','AYABACA','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('200201','PIURA ','AYABACA','AYABACA ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('200202','PIURA ','AYABACA','FRIAS');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('200203','PIURA ','AYABACA','JILILI  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('200204','PIURA ','AYABACA','LAGUNAS ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('200205','PIURA ','AYABACA','MONTERO ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('200802','PIURA ','SECHURA','BELLAVISTA DE LA UNIÓN  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('200803','PIURA ','SECHURA','BERNAL  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('200804','PIURA ','SECHURA','CRISTO NOS VALGA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('200805','PIURA ','SECHURA','VICE');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('200806','PIURA ','SECHURA','RINCONADA LLICUAR');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('210000','PUNO', '','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('210100','PUNO','PUNO','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('210101','PUNO','PUNO','PUNO');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('210102','PUNO','PUNO','ACORA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('210103','PUNO','PUNO','AMANTANI');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('210104','PUNO','PUNO','ATUNCOLLA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('210105','PUNO','PUNO','CAPACHICA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('210106','PUNO','PUNO','CHUCUITO');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('210107','PUNO','PUNO','COATA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('210108','PUNO','PUNO','HUATA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('210109','PUNO','PUNO','MAÑAZO  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('211306','PUNO','YUNGUYO','TINICACHI');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('211307','PUNO','YUNGUYO','UNICACHI');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('220000','SAN MARTÍN' , '','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('220100','SAN MARTÍN','MOYOBAMBA ','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('220101','SAN MARTÍN','MOYOBAMBA ','MOYOBAMBA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('220102','SAN MARTÍN','MOYOBAMBA ','CALZADA ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('220103','SAN MARTÍN','MOYOBAMBA ','HABANA  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('220104','SAN MARTÍN','MOYOBAMBA ','JEPELACIO');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('220105','SAN MARTÍN','MOYOBAMBA ','SORITOR ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('220106','SAN MARTÍN','MOYOBAMBA ','YANTALO ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('220200','SAN MARTÍN','BELLAVISTA','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('220603','SAN MARTÍN','MARISCAL CÁCERES','HUICUNGO');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('220604','SAN MARTÍN','MARISCAL CÁCERES','PACHIZA ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('220605','SAN MARTÍN','MARISCAL CÁCERES','PAJARILLO');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('220700','SAN MARTÍN','PICOTA','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('220701','SAN MARTÍN','PICOTA','PICOTA  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('220702','SAN MARTÍN','PICOTA','BUENOS AIRES');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('221003','SAN MARTÍN','TOCACHE','POLVORA ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('221004','SAN MARTÍN','TOCACHE','SHUNTE  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('221005','SAN MARTÍN','TOCACHE','UCHIZA  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('230000','TACNA ' , '','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('230100','TACNA ','TACNA ','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('230101','TACNA ','TACNA ','TACNA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('230102','TACNA ','TACNA ','ALTO DE LA ALIANZA  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('230103','TACNA ','TACNA ','CALANA  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('230407','TACNA ','TARATA','TARUCACHI');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('230408','TACNA ','TARATA','TICACO  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('240000','TUMBES' , '','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('240100','TUMBES','TUMBES','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('240101','TUMBES','TUMBES','TUMBES  ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('240102','TUMBES','TUMBES','CORRALES');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('240304','TUMBES','ZARUMILLA ','PAPAYAL ');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('250000','UCAYALI' , '','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('250100','UCAYALI','CORONEL PORTILLO','');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('250101','UCAYALI','CORONEL PORTILLO','CALLERIA');
INSERT INTO ubigeo (id,departamento,provincia,distrito) VALUES ('250102','UCAYALI','CORONEL PORTILLO','CAMPOVERDE  ');
